version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        command: python manage.py runserver
        volumes:
            - '.:/app'
        environment:
            - FLASK_ENV=development
        depends_on:
            - redis
    redis:
        image: 'redis:3.0-alpine'
        command: redis-server --requirepass devpassword
        volumes:
          - 'redis:/var/lib/redis/data'
        ports:
          - '6379:6379'
    celery:
        build: .
        command: celery worker -B -l info -A praylink.tasks.celery_app 
        volumes:
          - '.:/app'

volumes:
  redis: