version: '3'
services:
    praylink:
        build: .
        ports:
            - "5000:5000"
        command: >
            gunicorn -b :5000 --name praylink --reload "praylink:app"
        volumes:
            - '.:/app'
        env_file:
            - '.env'
        depends_on:
            - celery
            - postgres

    postgres:
        image: 'postgres:9.5'
        env_file:
            - '.env'
        volumes:
            - 'postgres_pl:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
    
    redis:
        image: 'redis:3.0-alpine'
        command: redis-server --requirepass devpassword
        volumes:
          - 'redis:/var/lib/redis/data'
        ports:
          - '6379:6379'
    
    celery:
        build: .
        command: celery worker -B -l info -A praylink.tasks.celery_app
        env_file:
          - '.env'
        volumes:
          - '.:/app'
        depends_on:
          - redis

    nginx:
        build: ./nginx/
        restart: always
        ports:
           - "80:80"
        volumes:
           - /www/static
        links:
            - praylink
        depends_on:
            - praylink

volumes:
  redis:
  postgres_pl: